services:
  apache:
    build:
      context: .
      dockerfile_inline: |
        from php:7-apache-bullseye
        add https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
        run chmod +x /usr/local/bin/install-php-extensions && \
            install-php-extensions pgsql
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - type: "bind"
        source: "./src"
        target: "/var/www/html"

  postgres:
    image: "postgres:16"
    command: "postgres -c log_destination=stderr -c log_statement=all"
    ports:
      - "127.0.0.1:11111:5432"
    environment:
      POSTGRES_USER: "apache"
      POSTGRES_PASSWORD: "passworda"
      POSTGRES_DB: "www"

  postgres-init:
    image: "postgres:16"
    entrypoint: /bin/sh
    command: -c "until PGPASSWORD=passworda psql -hpostgres -Uapache -f /init.sql www >/dev/null 2>&1; do echo waiting...; sleep 1; done"
    volumes:
      - type: "bind"
        source: "./init.sql"
        target: "/init.sql"
    depends_on:
      - "postgres"
